### ISSUE TITLE
how to install lib?

### ISSUE THREAD

**Issue by mrgloom** [cudamat/cudamat#25]
how to install lib?

it will be good if I can install it using pip like "pip install cudamat"

on win xp x32 I run make in folder and then run python test_cudamat.py

but it gives me error

Traceback (most recent call last):
  File "test_cudamat.py", line 4, in <module>
    import cudamat as cm
  File "C:\Documents and Settings\User\╨рсюўшщ ёЄюы\cudamat-master\cudamat-mas
ter\cudamat.py", line 8, in <module>
    _cudamat = ct.cdll.LoadLibrary('libcudamat.dll')
  File "C:\Python27\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126]

it seems that dll is missing?

I have only .so and .lib files.

if I rename .so to .dll in makefile I get error

Traceback (most recent call last):
  File "test_cudamat.py", line 4, in <module>
    import cudamat as cm
  File "C:\Documents and Settings\User\╨рсюўшщ ёЄюы\cudamat-master\cudamat-mas
ter\cudamat.py", line 12, in <module>
    _cudamat.get_last_cuda_error.restype = ct.c_char_p
  File "C:\Python27\lib\ctypes\__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'get_last_cuda_error' not found

**Comment by f0k** [comment]
In the meantime, cudamat is installable via pip (from a local checkout, there's no PyPI release yet); see the [installation instructions](https://github.com/cudamat/cudamat/blob/master/INSTALL.md).

Could you please check what exactly you need to change to compile on Windows? Just replace all occurrences of the useless `extern` keyword with `__declspec(dllexport)` (except for the occurrence in `extern "C"`)? If so, then I'll just add the necessary `ifdef` magic. Unfortunately, I don't have a Windows box to test this myself, so your help would be appreciated!

**Comment by mrgloom** [comment]
I think you can make it instalable from github like done here:
http://danielnouri.org/notes/2014/12/17/using-convolutional-neural-nets-to-detect-facial-keypoints-tutorial/
something like:
pip install -r https://raw.githubusercontent.com/dnouri/kfkd-tutorial/master/requirements.txt
pip install -r https://raw.githubusercontent.com/dnouri/kfkd-tutorial/master/requirements-2.txt

*>Just replace all occurrences of the useless extern keyword with __declspec(dllexport) (except for the >occurrence in extern "C")*
I think so,but it was long ago, for example in cudamat-win `DLLEXPORT extern` used.

**Comment by f0k** [comment]
> I think you can make it instalable from github

It already is installable from github via pip, there's nothing to be done for that, you can just run `pip install git+https://github.com/cudamat/cudamat.git`. I find it easier to keep track of updates when I have a local clone, though (i.e., check if there are upstream changes, pull them in and install again; or install in develop mode right away and just recompile if needed).

> I think so,but it was long ago

If you still have Windows available, I've created a PR with Windows support two weeks ago and am hoping for somebody to test it: #42
Would be nice if you could help out there!
