### ISSUE TITLE
Construct a matrix from a list of vectors

### ISSUE THREAD

**Issue by traxair** [cudamat/cudamat#37]
I have a list of vectors that I want to stack in a Matrix. Right now I am using gnumpy which uses cudamat under the hood.

This is my code
```
    arrays_size = vectors[0].size
    stack = gnumpy.zeros([arrays_size, len(arrays)])
    for i in range(len(arrays)):
        stack[:, i] = arrays[i]
```
When I profile this code I see a lot of synchronization steps because of the multiple assignments in Python. Is there a way to do the foor loop all at once?

**Comment by f0k** [comment]
I'm closing this Issue because the question seems to have been answered. Feel free to reopen if you think `cudamat` should do anything different.
