### ISSUE TITLE
CUDAMatrix has no attribute ones

### ISSUE THREAD

**Issue by tasptz** [cudamat/cudamat#44]
in check_ones_matrix(min_size)
       1181 
       1182 def check_ones_matrix(min_size):
    -> 1183     if min_size > CUDAMatrix.ones.shape[0]:
       1184         raise CUDAMatException(
       1185             'Not enough memory allocated for reduction. '
    AttributeError: type object 'CUDAMatrix' has no attribute 'ones'

I tried the example from the documentation and `A.sum(axis=0, target=col_sums)` gave the error above.

**Comment by f0k** [comment]
Did you call `cm.cublas_init()` as in the example? This initializes cuBLAS and also allocates the array of ones used to turn reduction operations into dot products.

**Comment by tasptz** [comment]
Yes, this solves the problem.
Sorry!
