### ISSUE TITLE
Sum gives wrong result

### ISSUE THREAD

**Issue by tasptz** [cudamat/cudamat#45]
What steps will reproduce the problem?

import numpy as np

x = np.array(np.random.random((100, 100)), dtype=np.float32)
x_sum = x.sum(axis=1)

import cudamat as cm
cm.cublas_init()

y = cm.CUDAMatrix(x)
y_sum = y.sum(axis=1).asarray()

print np.abs(x_sum - y_sum).sum()

z = cm.CUDAMatrix(x)
z_sum = z.asarray().sum(axis=1)

print np.abs(x_sum - z_sum).sum()

What is the expected output? What do you see instead?

Two numbers near zero.

35255.2
0.000637054

What version of the product are you using? On what operating system?

commit af7d9cabf39b9232d3f5aac648a721fd54ea9acc

all unit tests pass!

Ubuntu 12.04.5 LTS \n \l 64 bit

Please provide any additional information below.

Python 2.7.3

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2014 NVIDIA Corporation
Built on Thu_Jul_17_21:41:27_CDT_2014
Cuda compilation tools, release 6.5, V6.5.12

+------------------------------------------------------+                       
| NVIDIA-SMI 340.29     Driver Version: 340.29         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 570     Off  | 0000:01:00.0     N/A |                  N/A |
| 42%   51C    P0    N/A /  N/A |      4MiB /  1279MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Compute processes:                                               GPU Memory |
|  GPU       PID  Process name                                     Usage      |
|=============================================================================|
|    0            Not Supported                                               |
+-----------------------------------------------------------------------------+

**Comment by f0k** [comment]
The error is here:
> print np.abs(x_sum - y_sum).sum()

In this line, `x_sum.shape` is `(100,)`, while `y_sum.shape` is `(100,1)`. Numpy treats the first one as a row vector, while the latter is a column vector, and will broadcast both such that `x_sum - y_sum` becomes a matrix of `(100,100)` that contains the pairwise differences of all elements in `x_sum` with all elements in `y_sum`. What you want to compute instead is one of:
```python
(x_sum - y_sum.ravel()).sum()
(x_sum[:,np.newaxis] - y_sum).sum()
```
The result of either of those is zero.
