### ISSUE TITLE
Support for ND arrays (or at least 3D) and data types other than 'float'?

### ISSUE THREAD

**Issue by somada141** [cudamat/cudamat#47]
Hi there, 

I realize cudamat was built predominantly to support floating-point linear-algebra operations but I've been wondering whether it would be feasible to extend it to arrays of different data types and higher dimensionality.

After having taken a quick look at the kernels in 'cudamat_kernels.cuh' I would think that a generalization wouldn't be so outlandish given that (recent versions of) CUDA support kernel templating (at least to base types).

In addition, as the arrays you're using are always flat 1D arrays I don't understand why CUDAMatrix has been restricted to 2D representations (or at least why no CUDAArray class) exists.

Are any such extensions planned for future? Such extensions would allow for image processing algorithms with short int values (thus saving memory) and which can either be vectorial (RGB components), multi-image datasets such as medical image data, or both.

Regardless, thank you for making cudamat available and keep up the good work!

**Comment by f0k** [comment]
Disclaimer: I haven't written cudamat, so I cannot comment on past decisions, I'm just the de-facto maintainer right now.

> I realize cudamat was built predominantly to support floating-point linear-algebra operations but I've been wondering whether it would be feasible to extend it to arrays of different data types and higher dimensionality. [...] Are any such extensions planned for future?

Not by me.

It would be possible to extend the `CUDAMatrix` class to handle matrices of arbitrary dimensionality and strides (similar to numpy), but that would probably slow down the kernels a bit so we'd need each kernel with and without support for non-contiguous input, selected dynamically depending on the strides. And several operations make use of the fact that we only have 2D input (e.g., `sum` is implemented via a dot product with a vector of ones), so they would need alternative implementations for higher-dimensional input. All in all, this would require considerable effort.

Similarly, it would be possible to extend the `CUDAMatrix` class to support data types other than 32-bit floating point. Somewhere I've seen a cudamat fork that supported both single- and double-precision floats using templates, but this was several years ago and I never found it again. Anyway, this should be a lot easier to implement than an extension to n-dimensional arrays. The major hurdle would be dealing with mixed data types.

If you want to extend cudamat in any of these directions, let me know and we can discuss required changes in detail. But before, you should check whether and which benefits it would provide over alternative CUDA libraries for Python (scikits.cuda, PyCUDA, possibly libgpuarray).

**Comment by somada141** [comment]
Thanks a lot for the response, I may have underestimated the effort to get either of those features off the ground :).

Given cudamat's kernel structure, what I wanted to write was a symbolic GPU calculation interface by combining cudamat with sympy but the dimensionality and data-type issues are rather restricting. Before I invest into extending cudamat, however, I will look into the alternative libraries you mentioned.

I guess I will close this issue for now :). Thanks for your help!

**Comment by f0k** [comment]
> what I wanted to write was a symbolic GPU calculation interface

Just to be sure you didn't miss it, that description would also fit [Theano](/Theano/Theano) to some extent.
