### ISSUE TITLE
What is the shape of the train data and its label in nn_example 

### ISSUE THREAD

**Issue by StevenLOL** [cudamat/cudamat#49]
Hi, I don't have the util , thus was unable to load the data  in nn example.

May I know what is the shape of training data and shape of training label?

**Comment by StevenLOL** [comment]
done

**Comment by f0k** [comment]
For anybody else stumbling across this, the data for the NN example is this one: https://code.google.com/p/cudamat/downloads/detail?name=mnist49.dat
For the RBM example, it's this one: https://code.google.com/p/cudamat/downloads/detail?name=mnist.dat
This should actually be documented somewhere, or changed to download and use one of the original files from Yann's website.

**Comment by StevenLOL** [comment]
Hi, @f0k  thanks you for putting the info there. 

I found the util.py under source code folder, so indeed I have that file.

For the shape of the data:

training data=train_x is in dim*m
training label=train_y is in K_ClassNumber*m 

The class label are in 1 of K encoding.
