### ISSUE TITLE
Installing cudamat Win 8.1 error (building 'cudamat.libcudamat' extension)

### ISSUE THREAD

**Issue by ankitdhall** [cudamat/cudamat#59]
I recently tried to install cudamat to use GPU for performance while running my neural networks on an nVidia GeForce 920M. On executing I encountered the following error. Any help on how to get rid of it would be appreciated.
Regards,
Ankit.

C:\Users\Ankit\Desktop\cudamat-master>python setup.py install
running install
running bdist_egg
running egg_info
writing cudamat.egg-info\PKG-INFO
writing top-level names to cudamat.egg-info\top_level.txt
writing dependency_links to cudamat.egg-info\dependency_links.txt
reading manifest file 'cudamat.egg-info\SOURCES.txt'
writing manifest file 'cudamat.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
building 'cudamat.libcudamat' extension
Traceback (most recent call last):
  File "setup.py", line 121, in <module>
    cmdclass={'build_ext': CUDA_build_ext})
  File "C:\Python27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\site-packages\setuptools\command\install.py", line 67, i
n run
    self.do_egg_install()
  File "C:\Python27\lib\site-packages\setuptools\command\install.py", line 109,
in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\site-packages\setuptools\command\bdist_egg.py", line 160
, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Python27\lib\site-packages\setuptools\command\bdist_egg.py", line 146
, in call_command
    self.run_command(cmdname)
  File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\site-packages\setuptools\command\install_lib.py", line 1
0, in run
    self.build()
  File "C:\Python27\lib\distutils\command\install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\site-packages\setuptools\command\build_ext.py", line 49,
 in run
    _build_ext.run(self)
  File "C:\Python27\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "setup.py", line 41, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Python27\lib\distutils\command\build_ext.py", line 448, in build_exte
nsions
    self.build_extension(ext)
  File "C:\Python27\lib\site-packages\setuptools\command\build_ext.py", line 174
, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Python27\lib\distutils\command\build_ext.py", line 498, in build_exte
nsion
    depends=ext.depends)
  File "C:\Python27\lib\distutils\msvc9compiler.py", line 546, in compile
    extra_postargs)
  File "setup.py", line 70, in spawn
    os.path.dirname(find_executable("cl.exe", PATH))
  File "C:\Python27\lib\ntpath.py", line 215, in dirname
    return split(p)[0]
  File "C:\Python27\lib\ntpath.py", line 180, in split
    d, p = splitdrive(p)
  File "C:\Python27\lib\ntpath.py", line 115, in splitdrive
    if len(p) > 1:
TypeError: object of type 'NoneType' has no len()

My Python version is:
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (
AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by f0k** [comment]
Sorry for the poor error message. The problem is that it cannot find "cl.exe" on your PATH. You need to install a recent enough version of the MSVC compiler for nvcc to work, and install cudamat from the MSVC console.

You may also try to compile cudamat manually: https://github.com/cudamat/cudamat/issues/57#issuecomment-155102315
Would be interesting to see if this works, as the current `setup.py` is quite a hack for Windows.

**Comment by ankitdhall** [comment]
I installed Visual Studio Express 2012 to get the MSVC. Encountered an error saying 'vcvars64.bat could'nt be found'. Found the solution from here: https://devtalk.nvidia.com/default/topic/589217/vs2012-express-and-cuda-5-5-error

Ran the first line
nvcc -c -O -o cudamat.obj cudamat.cu
and received the following errors:

C:\Users\Ankit\Desktop\cudamat-master\cudamat>nvcc -c -O -o cudamat.obj cudamat.
cu
cudamat.cu
C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\INCLUDE\crtdefs.h(430): e
rror: invalid redeclaration of type name "size_t"

C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\INCLUDE\new(54): error: f
irst parameter of allocation function must be of type "size_t"

C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\INCLUDE\new(58): error: f
irst parameter of allocation function must be of type "size_t"

C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\INCLUDE\new(70): error: f
irst parameter of allocation function must be of type "size_t"

C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\INCLUDE\new(82): error: f
irst parameter of allocation function must be of type "size_t"

C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\INCLUDE\new(87): error: f
irst parameter of allocation function must be of type "size_t"

C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\INCLUDE\new(90): error: f
irst parameter of allocation function must be of type "size_t"

c:\program files\nvidia gpu computing toolkit\cuda\v7.5\include\common_functions
.h(101): error: first parameter of allocation function must be of type "size_t"

c:\program files\nvidia gpu computing toolkit\cuda\v7.5\include\common_functions
.h(102): error: first parameter of allocation function must be of type "size_t"

c:\program files\nvidia gpu computing toolkit\cuda\v7.5\include\common_functions
.h(200): error: first parameter of allocation function must be of type "size_t"

c:\program files\nvidia gpu computing toolkit\cuda\v7.5\include\common_functions
.h(201): error: first parameter of allocation function must be of type "size_t"

c:\program files\nvidia gpu computing toolkit\cuda\v7.5\include\sm_20_intrinsics
.hpp(110): error: asm operand type size(8) does not match type/size implied by c
onstraint 'r'

12 errors detected in the compilation of "C:/Users/Ankit/AppData/Local/Temp/tmpx
ft_00001de4_00000000-8_cudamat.cpp1.ii".


I used the VS2012 x86 Native Tools Command Prompt to run the above.
I'm still stuck, unable to install cudamat.

Regards,
Ankit

**Comment by ankitdhall** [comment]
I tried the same with VS2012 x64 Cross Tools Cmd and it didn't give any errors initially,
C:\Users\Ankit\Desktop\cudamat-master\cudamat>
C:\Users\Ankit\Desktop\cudamat-master\cudamat>nvcc -c -O -o cudamat.obj cudamat.
cu
cudamat.cu

C:\Users\Ankit\Desktop\cudamat-master\cudamat>nvcc -c -O -o cudamat_kernels.obj
cudamat_kernels.cu
cudamat_kernels.cu
cudamat_kernels.cu(747): warning: division by zero

cudamat_kernels.cu(747): warning: division by zero

cudamat_kernels.cu(771): warning: division by zero

cudamat_kernels.cu(771): warning: division by zero

cudamat_kernels.cu(747): warning: division by zero

cudamat_kernels.cu(747): warning: division by zero

cudamat_kernels.cu(771): warning: division by zero

cudamat_kernels.cu(771): warning: division by zero


C:\Users\Ankit\Desktop\cudamat-master\cudamat>nvcc --shared -o cudamat.dll cudam
at.obj cudamat_kernels.obj -lcublas
cudamat.obj
cudamat_kernels.obj
   Creating library cudamat.lib and object cudamat.exp

But while running the tests, this is what I got,

C:\Users\Ankit\Desktop\cudamat-master\test>nosetests
EE
======================================================================
ERROR: Failure: ImportError (No module named cudamat)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\loader.py", line 413, in loadTestsFro
mName
    addr.filename, addr.module)
  File "C:\Python27\lib\site-packages\nose\importer.py", line 47, in importFromP
ath
    return self.importFromDir(dir_path, fqname)
  File "C:\Python27\lib\site-packages\nose\importer.py", line 94, in importFromD
ir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\Users\Ankit\Desktop\cudamat-master\test\test_cudamat.py", line 3, in
<module>
    import cudamat as cm
ImportError: No module named cudamat

======================================================================
ERROR: Failure: ImportError (No module named cudamat)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\loader.py", line 413, in loadTestsFro
mName
    addr.filename, addr.module)
  File "C:\Python27\lib\site-packages\nose\importer.py", line 47, in importFromP
ath
    return self.importFromDir(dir_path, fqname)
  File "C:\Python27\lib\site-packages\nose\importer.py", line 94, in importFromD
ir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\Users\Ankit\Desktop\cudamat-master\test\test_learn.py", line 4, in <m
odule>
    import cudamat as cm
ImportError: No module named cudamat

----------------------------------------------------------------------
Ran 2 tests in 0.266s

FAILED (errors=2)

**Comment by f0k** [comment]
> ImportError: No module named cudamat

This means `cudamat` is not on your Python path. But at least it seems that you've been able to compile the cudamat extension. There are two ways now:

1. Try installing it the ordinary way again, now that you've got a command line that allows you to compile it. I.e., try `python setup.py install` again.
2. Alternatively, repeat the steps for `cudalearn`: Compile `learn.cu` and `learn_kernels.cu`, then link it together to produce `cudalearn.dll`. Checking again, you actually need to rename the files to `libcudamat.dll` and `libcudalearn.dll` (and possibly the `.lib` and `.exp` files as well). Then run `python setup.py develop` to add your cudamat directory to the Python path. You will need to keep it around then (feel free to move it from the Desktop to some more suitable permanent location).

**Comment by ankitdhall** [comment]
I tried installing it using
python setup.py install
but received the following error:
C:\Users\Ankit\Desktop\cudamat-master>python setup.py install
running install
running bdist_egg
running egg_info
writing cudamat.egg-info\PKG-INFO
writing top-level names to cudamat.egg-info\top_level.txt
writing dependency_links to cudamat.egg-info\dependency_links.txt
reading manifest file 'cudamat.egg-info\SOURCES.txt'
writing manifest file 'cudamat.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
copying cudamat\cudamat.py -> build\lib.win32-2.7\cudamat
running build_ext
building 'cudamat.libcudamat' extension
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\bin\nvcc.exe --compiler-
bindir "C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\BIN\x86_amd64" -c
 -IC:\Python27\include -IC:\Python27\PC cudamat/cudamat.cu -o build\temp.win32-2
.7\Release\cudamat/cudamat.obj -O --ptxas-options=-v --compiler-options=/nologo,
/Ox,/MD,/W3,/GS-,/DNDEBUG
cudamat.cu
c:\program files\nvidia gpu computing toolkit\cuda\v7.5\include\host_config.h(12
9) : fatal error C1189: #error :  -- unsupported Microsoft Visual Studio version
! Only the versions 2010, 2012, and 2013 are supported!
error: command 'nvcc' failed with exit status 2

Then, I tried using the second way. Compiled the files like before.
C:\Users\Ankit\Desktop\cudamat-master\cudamat>nvcc -c -O -o learn.obj learn.cu
learn.cu

C:\Users\Ankit\Desktop\cudamat-master\cudamat>nvcc -c -O -o learn_kernels.obj le
arn_kernels.cu
learn_kernels.cu

C:\Users\Ankit\Desktop\cudamat-master\cudamat>nvcc --shared -o cudalearn.dll lea
rn.obj learn_kernels.obj -lcublas
learn.obj
learn_kernels.obj
   Creating library cudalearn.lib and object cudalearn.exp

Renamed them as:
libcudalearn.dll
libcudalearn.exp
libcudamat.dll
libcudamat.exp

Finally, ran the python setup.py develop, ended up with the following,
C:\Users\Ankit\Desktop\cudamat-master>python setup.py develop
running develop
running egg_info
writing cudamat.egg-info\PKG-INFO
writing top-level names to cudamat.egg-info\top_level.txt
writing dependency_links to cudamat.egg-info\dependency_links.txt
reading manifest file 'cudamat.egg-info\SOURCES.txt'
writing manifest file 'cudamat.egg-info\SOURCES.txt'
running build_ext
building 'cudamat.libcudamat' extension
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\bin\nvcc.exe --compiler-
bindir "C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\BIN\x86_amd64" -c
 -IC:\Python27\include -IC:\Python27\PC cudamat/cudamat.cu -o build\temp.win32-2
.7\Release\cudamat/cudamat.obj -O --ptxas-options=-v --compiler-options=/nologo,
/Ox,/MD,/W3,/GS-,/DNDEBUG
cudamat.cu
c:\program files\nvidia gpu computing toolkit\cuda\v7.5\include\host_config.h(12
9) : fatal error C1189: #error :  -- unsupported Microsoft Visual Studio version
! Only the versions 2010, 2012, and 2013 are supported!
error: command 'nvcc' failed with exit status 2

I am still using the same command line as before.

**Comment by f0k** [comment]
> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\bin\nvcc.exe --compiler-
bindir "C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\BIN\x86_amd64"

It seems you still have a wrong version of the compiler in your PATH variable. You can do "echo %PATH%" to see what the path is. It should only contain MSVC 2012, the one you installed. It's interesting that running `nvcc` manually works, though...

> Finally, ran the python setup.py develop

Ah yes, forgot that it will try to still compile everything. You will need to manually add `C:\Users\Ankit\Desktop\cudamat-master` to your PYTHONPATH then. This seems to be the way to go (I don't have Windows so I can't check): http://stackoverflow.com/a/30728643

**Comment by ankitdhall** [comment]
I added the path and it worked. The problem was with incompatible 32bit Python and 64bit library. Thanks for the help.
Cheers. :)
