### ISSUE TITLE
On "minmax" method in class CUDAMatrix

### ISSUE THREAD

**Issue by konts6102** [cudamat/cudamat#60]
Hi, all 

Is there the method "minmax" in class CUDAMatrix for some version of cudamat?

I am trying to run ctc-stanford scripts, and then minmax method is called  for cuda.cuda.CUDAMatrix objects. For example,  self.hActsFor.minmax(0.0,self.maxAct,col=0), where hActsFor is such kind of object.

**Comment by f0k** [comment]
They're using their own fork of cudamat, as explained in their Readme: https://github.com/amaas/stanford-ctc
Would be cool to include those changes in the main branch, though. I've asked @awni last summer and he said he'd be happy to send a pull request although it might take a while. Feel free to have a stab at it!
