### ISSUE TITLE
Using "make" from deepnet bundle

### ISSUE THREAD

**Issue by Rietaros** [cudamat/cudamat#64]
Hello, I want to start using deepnet (https://github.com/nitishsrivastava/deepnet). For some reason it was built on top of cudamat, so I need to install and i read the tutorial. But I have trouble while i call 'make' file like this:

~/Documents/deepnet-master/cudamat$ sudo make
nvcc -O3 \
		-v \
		-gencode=arch=compute_10,code=sm_10 \
	  -gencode=arch=compute_20,code=sm_20 \
		-gencode=arch=compute_30,code=sm_30 \
		--compiler-options '-fPIC' -o libcudamat.so \
		--shared cudamat.cu cudamat_kernels.cu -lcublas -L
nvcc fatal   : argument expected after '-L'
make: *** [libcudamat.so] Error 255

why it happen?
thank you

**Comment by f0k** [comment]
deepnet comes with its own bundled cudamat, which is different from the version here. Please direct any support questions there.

Anyway, have a look at the Makefile: https://github.com/nitishsrivastava/deepnet/blob/master/cudamat/Makefile
It uses `-L$(CUDA_LIB)`. If the environment variable `CUDA_LIB` is empty, it will result in `-L` with a missing argument. `sudo CUDA_LIB=/usr/local/cuda/lib64 make` should work.
