### ISSUE TITLE
CUDAMatrix.init_random crashes on Windows with Python 3

### ISSUE THREAD

**Issue by BCSharp** [cudamat/cudamat#67]
I have successfully installed the latest cudamat from the master branch (pip reported cudamat-0.3). My environment is:

 * Windows 10 64-bit
 * Anaconda Python 3.4.4 (64-bit)
 * Using Visual Studio 2010 (AKA v. 10.0)
 * CUDA 7.5
 * GeForce GTX 650 Ti

I am using Python 3.4 because neither Visual Studio 9.0 (required for Python 2.7) nor Visual Studio 14.0 (required for Python 3.5) is supported by CUDA 7.5.

The compilation goes fine, so do all the tests but one: test_random.

This test crashes the process on the call `cm.CUDAMatrix.init_random(1)`
Within `init_random` the offending line is:
```
        err_code = _cudamat.init_random(CUDAMatrix.rnd_state_p,
                                        ct.c_int(seed),
                                        cudamat_path)
```

The reason is that  `cudamat_path` is Unicode under Python 3, while `_cudamat.init_random` has signature
`int init_random(rnd_struct* rnd_state, int seed, char* cudamatpath)`

When I change the function signature to
`int init_random(rnd_struct* rnd_state, int seed, wchar_t* cudamatpath)`
and use `_wfopen` instead of `fopen` within the function, everything works fine. 

This is just a quick fix, not a solution; a proper solution should work for both Python 2 and 3 series, as well as Windows and non-Windows OS-es.

**Comment by f0k** [comment]
> I am using Python 3.4 because neither Visual Studio 9.0 (required for Python 2.7) nor Visual Studio 14.0 (required for Python 3.5) is supported by CUDA 7.5.

I *think* these versions should be independent -- you should be able to use any nvcc-supported compiler for the CUDA code. We're just creating a shared library (or DLL) to be loaded via `ctypes`, not a complete Python module.

> The reason is that cudamat_path is Unicode under Python 3

Oh, nice catch! Maybe an easier solution will be to convert the path to a byte string in Python 3, so we can use the same compiled library for Python 2 and 3. Maybe it would even be enough to declare the argument types for `ctypes` and it will do the conversion automatically.

Would you be willing to try finding a solution that modifies the Python code only? I currently don't have a Windows box with CUDA to work on, but I can at least check Python 2 and 3 under Linux.

**Comment by BCSharp** [comment]
>> I am using Python 3.4 because neither Visual Studio 9.0 (required for Python 2.7) nor Visual Studio 14.0 (required for Python 3.5) is supported by CUDA 7.5.

> I think these versions should be independent

Good to know. However, my understanding was that the problem was not so much which compiler is used but which C runtime standard library the code is compiled against. cudamat uses e.g. `fopen`, which is in the C lib, and it is better if it is the same C lib version that python.exe uses. 

Anyway, I will get Python 3.4 working here and then submit a pull request. A quick look at the code makes me think there may be more places where Python 3 unicode handling will cause problems. Maybe I will do a code review to check them out. One thing that got my attention is:
```python
def get_last_cuda_error():
    return str(_cudamat.get_last_cuda_error())
```
I believe it will not work as expected in Python 3 but I will have to test it.


Good you can test the changes under Linux. At the moment, I do not have a Linux box with CUDA GPU.

>  Maybe it would even be enough to declare the argument types for  ctypes  and it will do the conversion automatically.

I don't think there is ever an automatic conversion from Unicode to byte string, because it depends on required encoding.

**Comment by f0k** [comment]
> cudamat uses e.g. `fopen`, which is in the C lib, and it is better if it is the same C lib version that python.exe uses.

Hmm, if cudamat doesn't pass on its file pointers to parts linked against a different C library, everything should be fine, shouldn't it?

> A quick look at the code makes me think there may be more places where Python 3 unicode handling will cause problems.

This is entirely possible. #43 didn't stumble across this. Maybe the problem with the path string you found is actually limited to Windows?

> I believe it will not work as expected in Python 3 but I will have to test it.

In case it doesn't work, I'd be fine with adding a very basic `if sys.version()[0] == 2` check on spot to determine the return type to use (but again, maybe `ctypes` can handle this for us).

> I don't think there is ever an automatic conversion from Unicode to byte string, because it depends on required encoding.

[Turns out there is](https://docs.python.org/2/library/ctypes.html#ctypes._FuncPtr.argtypes):
> For example, a c_char_p item in the argtypes tuple will convert a unicode string passed as argument into a byte string using ctypes conversion rules.

A side question is whether this will break cudamat when installed to a directory containing unicode characters. In Linux, it seems UTF8 is the way to go:
```
$ mkdir -p bäm/foo
$ python3
>>> import os
>>> os.listdir('bäm')
['foo']
>>> os.listdir('bäm'.encode('utf8'))
[b'foo']
>>> os.listdir('bäm'.encode('utf16'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: listdir: embedded NUL character in path
```
Not sure what happens under the hood, though.

**Comment by f0k** [comment]
> Not sure what happens under the hood, though.

Tried the same with `init_random`. It doesn't even check if the file can be opened successfully:
```
>>> cm.init_random(cudamat.CUDAMatrix.rnd_state_p, ctypes.c_int(123), '/does/not/exist')
0
>>> cm.init_random(cudamat.CUDAMatrix.rnd_state_p, ctypes.c_int(123), '/tmp/bäm/rnd_multipliers_32bit.txt')
0
>>> cm.init_random(cudamat.CUDAMatrix.rnd_state_p, ctypes.c_int(123), '/tmp/bäm/rnd_multipliers_32bit.txt'.encode('utf8'))
0
>>> cm.init_random(cudamat.CUDAMatrix.rnd_state_p, ctypes.c_int(123), '/tmp/bäm/rnd_multipliers_32bit.txt'.encode('utf16'))
Segmentation fault (core dumped)
```
But again, it likes UTF8, and probably `unicode` is passed as an UTF8-encoded string if we don't encode it to a `bytes` string ourselves.

**Comment by BCSharp** [comment]
>> cudamat uses e.g. fopen, which is in the C lib, and it is better if it is the same C lib version that python.exe uses.

> Hmm, if cudamat doesn't pass on its file pointers to parts linked against a different C library, everything should be fine, shouldn't it?

Yes. It should. However, it is not that simple. I just tried to install cudamat under Python27 from Anaconda: pip/setuptools insist on using VC2009 libs and includes, but then nvcc refuses to compile claiming VC2009 is not supported. Maybe it is Anaconda-specific problem. Maybe there is a workaround, but I am not going to pursue it; unfortunately, this means I cannot check changes under Python27 on Windows.

> But again, it likes UTF8, and probably unicode is passed as an UTF8-encoded string if we don't encode it to a bytes string ourselves.

When using unicode paths in Python 3, they will be automatically converted to proper byte encoding depending on filesystem encoding. On Linux it will be whatever is configured by LC_LANG or other LC_* (which for most modern Linuxes will be UTF-8). On Windows it will be MBCS.

> For example, a c_char_p item in the argtypes tuple will convert a unicode string passed as argument into a byte string using ctypes conversion rules.

This means it may get it right, indeed. I tried with:
```python
_cudamat.init_random.argtypes = [ct.POINTER(rnd_struct), ct.c_int, ct.c_char_p]
```

But it does not work:
```
======================================================================
ERROR: test_cudamat.test_random
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Tools\Anaconda\envs\cudamat34\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Code\NVIDIA\cudamat\test\test_cudamat.py", line 1089, in test_random
    cm.CUDAMatrix.init_random(1)
  File "C:\Tools\Anaconda\envs\cudamat34\lib\site-packages\cudamat\cudamat.py", line 255, in init_random
    cudamat_path)
ctypes.ArgumentError: argument 3: <class 'TypeError'>: wrong type

----------------------------------------------------------------------
```

Did I get the `argtypes` wrong?


My current solution is:
```python
        if sys.version_info.major >= 3:
            cudamat_path = cudamat_path.encode(sys.getfilesystemencoding())
```
It works fine.

>  It doesn't even check if the file can be opened successfully:
```
Segmentation fault (core dumped)
```

Therefore I want to propose adding test if the result of fopen is NULL and return an error code if it is. The error code will then be converted to a regular python exception, rather than triggering a core dump. I can submit a PR for it too.

**Comment by f0k** [comment]
> pip/setuptools insist on using VC2009 libs and includes, but then nvcc refuses to compile claiming VC2009 is not supported.

Ah, sorry, I forgot how things were set up in cudamat. I think the solution will be #53, so cudamat doesn't use setuptool's C compiler machinery -- `nvcc` is platform-independent already, supporting the same command line arguments for Windows and *nix, so we can use it directly.

> When using unicode paths in Python 3, [...]

Thanks for the explanation!

> Did I get the `argtypes` wrong?

Looking further, it seems "unicode string" may refer to the `unicode` type in Python 2 only: http://stackoverflow.com/questions/27285405/how-can-ctypes-be-used-to-parse-unicode-strings#comment43039374_27285405
That comment also tells what the mysterious "ctypes conversion rules" are referring to: https://docs.python.org/2/library/ctypes.html#ctypes.set_conversion_mode
The default encoding for Windows is `mbcs`, which would be fine -- so most probably it is just not triggered at all for Python 3 `str` objects.

> My current solution is:

That's fine by me, go for it! This will work in Linux as well.

> Therefore I want to propose adding test if the result of fopen is NULL and return an error code if it is.

Yes, please, this would be appreciated! You can just include this in a single PR of two commits.
