### ISSUE TITLE
rbm_cudamat.py and nn_cudamat.py both crashed after 30 Epoch

### ISSUE THREAD

**Issue by madhurgoel** [cudamat/cudamat#71]
Following is the error line repeated multiple times:
Exception cudamat.cudamat.CUDAMatException: CUDAMatException('CUBLAS error.',) in
 \<bound method CUDAMatrix.\_\_del\_\_ of \<cudamat.cudamat.CUDAMatrix object at 0x7fbe47b16950>> ignored

I am using CUDA 7.5 with GTX980TI on Ubuntu 14.04 LTS
all tests(nosetests, python ../examples/bench_cudamat.py) as mentioned in INSTALL.md worked perfectly. Any help is appreciable...

**Comment by madhurgoel** [comment]
In both the cases the cm.cublas_shutdown() is causing the error.

**Comment by f0k** [comment]
Thanks for the report! It's a duplicate of #19, let's continue there. From my investigations, it seemed like an attempted double free, but it's not clear how this is possible. Any steps towards a solution would be appreciated (we could catch and silence the exception, but it would be better to find the cause).
