### ISSUE TITLE
make not working with cudamat

### ISSUE THREAD

**Issue by naif1980s** [cudamat/cudamat#72]
hi

i have followed the steps in this blog (http://www.pyimagesearch.com/2014/10/13/deep-learning-amazon-ec2-gpu-python-nolearn/#comment-404274)  and after i move to the cudamat folder by typing ( cd cudamat ) 
then make.. i get this error ( make: *** No targets specified and no makefile found.  Stop.)  

any advice?? thx in advance

**Comment by naif1980s** [comment]
i just wanted to mention that i am using EC2 from amazon, and using ubuntu 14 ..

**Comment by f0k** [comment]
Since #31, cudamat doesn't use a makefile any more. Installation instructions are given in the [installation documentation](https://github.com/cudamat/cudamat/blob/master/INSTALL.md).
