### ISSUE TITLE
Problems when installing cudamat on windows

### ISSUE THREAD

**Issue by ofajardo** [cudamat/cudamat#81]
Hi, 

I have issues when installing cudamat on windows. I am using windows 10 64 bits, with python 2.7.12 (Anaconda 4.2). This issue is kind of similar to #69 but I get different errors. 

First of all, I installed CUDA and have a functional nvcc command. I have tried to install cudamat wither by pip or directly running setup.py and both failed with the same kind of errors.

First, as it is suggested on https://wiki.python.org/moin/WindowsCompilers that one should use the same C++ compiler version as the python version, as I am using python 2.7 I try to install with visual C++ 9. This gives the following error:

    Microsoft (R) C/C++ Optimizing Compiler Version 15.00.30729.01 for x64
    Copyright (C) Microsoft Corporation.  All rights reserved.

    tmpxft_00001e0c_00000000-1.cpp
    nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
    nvcc fatal   : Host compiler targets unsupported OS.
    error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\bin\\nvcc.exe' failed with exit status 1

Then, I read here http://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html#axzz4T75SPmzM that actually only C++ 11 onwards is supported. Therefore I tried with C++ 14 and then I get a different error:

nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
    cudamat.obj
    cudamat_kernels.obj
    LINK : fatal error LNK1181: cannot open input file 'ID=2.obj'
    error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\bin\\nvcc.exe' failed with exit status 2

Is there anything that can be done? or it is just simply not going to work and I have to migrate to python 3.5? (but then I would get the problems as #69 I guess).

Has anybody been able to correctly install cudamat on windows?

thanks!

**Comment by ofajardo** [comment]
I just tried the solution on #57 (compiling manually). Compiling works well. when I try to import cudamat however, I get the following which I dont understand because libcudamat.dll is present in the cudamat directory. Any idea?
I just found that I am actually working on python 3.5 ! (I activated a virtual env from somebody else and I did nto know it was using 3.5 ver.)

>>> import cudamat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Otto\Downloads\cudamat-master\cudamat\cudamat.py", line 19, in <module>
    _cudamat = load_library('libcudamat')
  File "C:\Users\Otto\Downloads\cudamat-master\cudamat\cudamat.py", line 17, in load_library
    basename + ext))
  File "C:\Program Files\Anaconda2\envs\phy\lib\ctypes\__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "C:\Program Files\Anaconda2\envs\phy\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] No se puede encontrar el módulo especificado

**Comment by ofajardo** [comment]
OK sorry, it was just a silly path problem. Now I can import correctly. I will try to test to see if it is really working.

**Comment by ofajardo** [comment]
Tests run OK. It means that the manual compiling solved the problem.

For the records, I am using python 3.5 on windows 10 64 bit. 
After installing CUDA, I installed C++ 2015 from here:
http://landinghub.visualstudio.com/visual-cpp-build-tools

after that, I used one of the prompts on C:\Program Files (x86)\Microsoft Visual C++ Build Tools, I think it was either the Visual C++ 2015 x86 x64 Cross Build Tools Command Prompt, or native 64 or MSBuild, dont remember anymore.

After that, I compiled manually as indicated on #57, created a cudamat folder on site packages and moved the necessary elements there. This seems to do the trick.

**Comment by f0k** [comment]
Just for the record, can you also try compiling with #79? A simple `pip install http://github.com/f0k/cudamat/archive/simplify-compile.zip` would do (with `--user` and/or `--upgrade --no-deps --force-reinstall` as needed). Thank you!

**Comment by ofajardo** [comment]
the building and installation seems to work. However, importing cudamat does not work, it seems that it fails to load the shared libraries

>>> import cudamat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Anaconda2\envs\phy\lib\site-packages\cudamat\__init__.py", line 1, in <module>
    from .cudamat import *
  File "C:\Program Files\Anaconda2\envs\phy\lib\site-packages\cudamat\cudamat.py", line 15, in <module>
    _cudamat = load_library('libcudamat')
  File "C:\Program Files\Anaconda2\envs\phy\lib\site-packages\cudamat\cudamat.py", line 13, in load_library
    basename + sysconfig.get_config_var('SO')))
  File "C:\Program Files\Anaconda2\envs\phy\lib\ctypes\__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "C:\Program Files\Anaconda2\envs\phy\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] No se puede encontrar el módulo especificado

**Comment by f0k** [comment]
Thank you for testing. Can you edit your `C:\Program Files\Anaconda2\envs\phy\lib\site-packages\cudamat\cudamat.py`, so `load_library` becomes:
```python
def load_library(basename):
    here = os.path.dirname(__file__) or os.path.curdir
    fn = os.path.join(here, basename + sysconfig.get_config_var('SO'))
    print(fn)
    print(os.path.listdir(here))
    return ct.cdll.LoadLibrary(fn)
```
Try importing the library again. It should now give us some hints what's going wrong.

**Comment by ofajardo** [comment]
Hmm, today I cannot reproduce the problem, cudamat is installing fine. I also re-installed and seems OK.

**Comment by ofajardo** [comment]
back from Xmas vacation, I reinstalled Anaconda, and then reinstalled cudamat with pip as you suggested. It imports fine, and tests run OK. So I guess it is confirmed that it is working as expected!

**Comment by SerialDev** [comment]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-0243508c6a8e> in <module>()
----> 1 import cudamat

C:\Users\Carlos\Anaconda3\lib\site-packages\cudamat\__init__.py in <module>()
----> 1 from .cudamat import *
      2 from . import learn

C:\Users\Carlos\Anaconda3\lib\site-packages\cudamat\cudamat.py in <module>()
     15     return ct.cdll.LoadLibrary(fn)
     16 
---> 17 _cudamat = load_library('libcudamat')
     18 
     19 _cudamat.get_last_cuda_error.restype = ct.c_char_p

C:\Users\Carlos\Anaconda3\lib\site-packages\cudamat\cudamat.py in load_library(basename)
     12     fn = os.path.join(here, basename + sysconfig.get_config_var('SO'))
     13     print(fn)
---> 14     print(os.path.listdir(here))
     15     return ct.cdll.LoadLibrary(fn)
     16 

AttributeError: module 'ntpath' has no attribute 'listdir'

**Comment by f0k** [comment]
> ```
> >      12     fn = os.path.join(here, basename + sysconfig.get_config_var('SO'))
> >      13     print(fn)
> > ---> 14     print(os.path.listdir(here))
> >      15     return ct.cdll.LoadLibrary(fn)
> ```
It should be `os.listdir`. But anyway, this is not part of the cudamat code, I guess you added this yourself?

Ah, I see, you corrected it afterwards and posted the output.

> ```
> C:\Users\Carlos\Anaconda3\lib\site-packages\cudamat\libcudamat.pyd
> ['cudamat.cu', 'cudamat.py', 'cudamat_kernels.cu', 'learn.cu', 'learn.py', 'learn_kernels.cu', 'libcudalearn.cp36-win_amd64.exp', 'libcudalearn.cp36-win_amd64.lib', 'libcudalearn.cp36-win_amd64.pyd', 'libcudamat.cp36-win_amd64.exp', 'libcudamat.cp36-win_amd64.lib', 'libcudamat.cp36-win_amd64.pyd', 'rnd_multipliers_32bit.txt', '__init__.py', '__pycache__']
> ```

So it tries to load `libcudamat.pyd` because `sysconfig.get_config_var('SO')` is set to `.pyd`. During compilation, though, `sysconfig.get_config_var('SO')` seems to have been set to `.cp36-win_amd64.pyd`. It seems you installed cudamat with a different Python interpreter than you used afterwards. You can try copying the files and rename them accordingly, but chances are that the two interpreters are not compatible. Try to figure out which interpreter you used for compiling and which one you used for importing cudamat. At the very least, they should produce the same output for `import sysconfig; print sysconfig.get_config_var('SO')`.
