### ISSUE TITLE
fp16

### ISSUE THREAD

**Issue by workingforfood** [cudamat/cudamat#95]
Hello, thanks for your awesome library. But i have one question, is there any way to modify it to use fp16? And how hard to do that. I want to process huge amount of data on gpu, and i don’t need accuracy of fp32 by the cost of its memory consumption. Can someone guide me in what direction i should move to solve such problem.

**Comment by f0k** [comment]
1. Do you have proper hardware support? On a GP100 chip (Tesla P100) or GV100 (Tesla V100) float16 is faster than float32, but on all other Pascal chips (up to Titan Xp) it's 1/64th of the performance of float32.
2. If you just need to save memory, you can still use float16 storage and float32 computation.
3. I guess modifying cudamat won't be the easiest option for you, unless you already have a ton of code using cudamat. There are other libraries that support imperative numpy-like GPU programming now, and are more feature-complete than cudamat. Have a look at [cupy](/cupy/cupy) or [PyTorch](/pytorch/pytorch), for example.

I'll close this issue for now -- if you think adding fp16 to cudamat would still be the best solution, feel free to reopen and we can have a closer look!
